// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      clean: {
        options: {
          force: true
        },
        bodule: "../../public/bodule_modules/<%= pkg.name %>/<%= pkg.version %>"
      },
      bodule: {
        options: {
          "package": grunt.file.readJSON('package.json')
        },
        bodule: {
          files: {
            '../../public/bodule_modules/<%= pkg.name %>/': '<%= pkg.main %>'
          }
        }
      }
    });
    grunt.loadTasks('../grunt-contrib-clean/tasks/');
    grunt.loadTasks('../grunt-bodule-wrapping/tasks/');
    return grunt.registerTask('default', ['clean', 'bodule']);
  };

}).call(this);
